# Generated by Django 3.2.8 on 2021-11-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_key', models.CharField(max_length=20, verbose_name='Llave Parametro')),
                ('parameter_value', models.CharField(max_length=50, verbose_name='Valor Parametro')),
                ('parameter_verbose', models.CharField(max_length=50, verbose_name='Valor para Mostrar')),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
    ]
